### ISSUE TITLE
allign footer to centre 

### ISSUE THREAD

**Issue by sha26pratyush** [sha26pratyush/byte-journey#6]
## Current State
The current state of the footer is shown in the picture below:
![image](https://github.com/sha26pratyush/byte-journey/assets/142671175/630dc51d-53b2-4b93-8f55-1049469bb780)

## What's the issue?
On zooming out the webpage, the footer is aligned towards the left of the page as shown in the picture below:
![image](https://github.com/sha26pratyush/byte-journey/assets/142671175/34cbe07c-3e49-4a5a-aa01-a5a350770940)

## Desired Result
The footer should be aligned towards the center even after zooming out the webpage. A sample is as shown in the below picture
![image](https://github.com/sha26pratyush/byte-journey/assets/142671175/9b561fa6-c5fe-4dbd-adc9-e1842fd7a63e)

---
Planning to solve this issue?<br>Please adhere to the [contribution guidelines](https://github.com/sha26pratyush/byte-journey/blob/main/docs/CONTRIBUTING.md).

**Comment by ag19bhoomi** [comment]
Hi Pratyush,

I hope you're doing well. 

Could you please assign this task to me? I believe I have the expertise and capacity to address this effectively.

Thank you for your attention to this matter. If you require any further information or assistance, please don't hesitate to reach out.

Best regards,
Bhoomi

**Comment by sha26pratyush** [comment]
Hello @ag19bhoomi,

I appreciate your willingness to contribute. It's great that you've grasped the problem at hand. Should you require any more guidance, feel free to ask. Also, remember to include the issue number when submitting the pull request.

Best regards,
Pratyush
